FROM openjdk:8-jre as builder
WORKDIR extracted
ADD target/*.jar app6.jar
RUN java -Djarmode=layertools -jar app6.jar extract

FROM openjdk:8-jre
WORKDIR application
COPY --from=builder extracted/dependencies/ ./
COPY --from=builder extracted/spring-boot-loader/ ./
COPY --from=builder extracted/snapshot-dependencies/ ./
COPY --from=builder extracted/application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]