server:
  port: 8084
spring:
  config:
    import: optional:configserver:http://localhost:8888/
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.type.mapping]": event:uz.abbos.OrderPlacedEvent
      group-id: notificationId
    template:
      default-topic: notificationTopic
  application:
    name: notification-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka