server:
  port: 0

spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411

  cloud:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.package: 'uz.abbos.OrderPlacedEvent'
      group-id: notificationId