spring:
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
  cloud:
    eureka:
      client:
        service-url:
          default-zone: http://localhost:8761/eureka
  zipkin:
    base-url: http://localhost:9411
