server:
  port: 8086
spring:
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.type.mapping]": event:uz.abbos.OrderPlacedEvent
      group-id: notificationId
    template:
      default-topic: notificationTopic
  application:
    name: notification-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
       defaultZone: http://eureka:password@localhost:8761/eureka