spring:
  kafka:
      bootstrap-servers:
        - broker:29092
  zipkin:
    base-url: http://localhost:9411
eureka:
   client:
     service-url:
       defaultZone: http://eureka:password@discovery-server:8761/eureka
