server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
       - id: product-service
         uri: lb://product-service
         predicates:
         - Path=/product
         - Method=GET, POST
       - id: order-service
         uri: lb://order-service
         predicates:
            - Path=/order
            - Method=GET,POST
#          discovery server route
       - id: discovery-server
         uri: http://discovery-server
         predicates:
            - Path=
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route:
          RouteDefinitionLocator : INFO
    root: INFO