server:
  port: 8080
spring:
  zipkin:
    base-url: http://localhost:9411
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8181/auth/realms/microservice-app
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka