server:
  port: 8181
spring:
  zipkin:
    base-url: http://localhost:9411
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/microservice-app
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
#  instance:
#    hostname: localhost
#    prefer-ip-address: true