server:
  port: 8080
spring:
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order_service_db
    username: postgres
    password: root
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

