server:
  port: 8082
spring:
  cloud:
    client:
      enabled: true
      fetch-registry: true
      service-url:
        default-zone: http://localhost:8761/eureka

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order_service_db
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: order-service