server:
  port: 8082
spring:
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/order_service_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

