server:
  port: 8083
spring:
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-order:5431/order_service_db
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
      bootstrap-servers:
        - broker:29092
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka

