server:
  port: 8083
spring:
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
      bootstrap-servers:
        - broker:29092
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka

