server:
  port: 8761
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false n
#  instance:
#    hostname: localhost
spring:
  application:
    name: discovery-server
  zipkin:
    base-url: http://localhost:9411