server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: true
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    locator:
      discovery:
        enabled: true
    enabled: true
  application:
    name: discovery-server
app:
  eureka:
    username: eureka
    password: password
