server:
  port: 8761
eureka:
#  instance:
#    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
  application:
    name: discovery-server
app:
  eureka:
    username: eureka
    password: password
