spring:
  zipkin:
    base-url: http://localhost:9411
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongo_db
      database: product
  datasource:
    driver-class-name:

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
server:
  port: 8081