server:
  port: 8081
spring:
  config:
    import: optional:configserver:http://localhost:8888/
  rabbitmq:
#    addresses: ${RABBITMQ_SERVICE_SERVICE_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_URSER_NAME:guest}
    password: ${RABBIT_MQ_URSER_PASSWORD:guest}
    host: ${RABBIT_MQ_HOST:localhost}
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    config:
      fail-fast: true
  application:
    name: product-service
management:
  endpoints:
    web:
      exposure:
        include: "*"




















  #  sleuth:
#    sampler:
#      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9411
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/product_db
#      database: product_db
#      port: 27017

#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka:password@localhost:8761/eureka
#  instance:
#    hostname: localhost