spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  data:
    mongodb:
      uri: mongodb://mongodb:27017/product_db
      database: product_db
      port: 27017
      host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
server:
  port: 8081