server:
  port: 8082
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inver_service_db
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: inventory-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
#  instance:
#    hostname: localhost

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: full
        decode404: true