server:
  port: 8083
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inver_service_db
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: inventory-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
    enabled: true
    fetch-registry: false