server:
  port: 8081
spring:
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inver_service_db
    username: postgres
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka