server:
  port: 8082
spring:
  config:
    import: optional:configserver:http://localhost:8888/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inver_service_db
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: inventory-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: full
        decode404: true