FROM openjdk:8-jre-slim-stretch as builder
WORKDIR extracted
ADD target/*.jar app.jar
RUN java -Djarmode=layertools -jar app.jar extract


FROM openjdk:8-jre-slim-stretch
WORKDIR application
COPY --from=builder extracted/dependencies/ ./
COPY --from=builder extracted/spring-boot-loader/ ./
COPY --from=builder extracted/snapshot-dependencies/ ./
ENTRYPOINT ["java","org.springframework.boot.loader.JarLauncher"]